In [1]:
#creating numpy/n-d arrays
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a2=np.array([[1,2,3],[3,4,5]])  #2d numpy array
a2 #printing a2

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
a3=np.zeros((2,3))  #Create matrix of 2*3 filled with zeros
a3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
a4=np.ones((3,3)) #Create matrix with 3*3 filled with 1
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a5=np.identity(5) #Creates an identity matrix of 5*5

In [9]:
a5 #prints a5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
a6=np.arange(10)
a6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a6=np.arange(5,16)
a6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
a6=np.arange(5,16,2)
a6


array([ 5,  7,  9, 11, 13, 15])

In [13]:
a=[1,2]
b=[5,6]
c=[0,0]
c=np.array([a,b,c])
print(c)

[[1 2]
 [5 6]
 [0 0]]


In [14]:
c

array([[1, 2],
       [5, 6],
       [0, 0]])

In [15]:
a7=np.linspace(10,20,10)  
#all the distances are linearly spaced like between 10 and 11.1111
#between 11.1111 and 12.2222 and so on
#lower range, upper range, space to make the ending to 20 from 10

In [16]:
a7


array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [17]:
a8=a7.copy()  #a7 numpy array is copied to a8

In [18]:
a8
#prints a8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])