Numpy Array Properties and Attributes

iniharu ma braket hundaina cause iniharu chai not function its an attribute of an numpy array

1. Shape  #prints matrix order

In [47]:
import numpy as np

In [48]:
a=np.arange(5)

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
a.shape

(5,)

In [51]:
a=np.array([[1,2],[3,4],[5,6]])

In [52]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
a.shape

(3, 2)

In [54]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
a.shape #3 rows and 2 columns

(3, 2)

In [56]:
a=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[4,5]]])
a

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [4, 5]]])

In [57]:
a.shape


(2, 3, 2)

In [58]:
a=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4]]])  #shows error  as should be either 2*2 or 2*3 matrix both
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [89]:
a=np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[4,5]],[[1,2],[3,4],[4,5]],[[1,2],[3,4],[4,5]],[[1,2],[3,4],[4,5]]])
a

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [4, 5]]])

In [90]:
a.shape  #5 rows and each row contains a grid of shape (3, 2). Each grid within a row is made up of elements arranged in 3 rows and 2 columns.


(5, 3, 2)

2. ndim

In [91]:
a.ndim  #prints dimension of matrix like (2,4) then 2 dimension if 1 then 1 dimension so on

3

In [ ]:
a1=np.zeros((2,4))

In [ ]:
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a1.ndim

2

In [ ]:
a2=np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2.ndim

1

3. Size   ---> no of items in an array is returned

In [62]:
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
a1.size

8

In [71]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:

a2.size

10

In [72]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [4, 5]]])

In [66]:
a.size

12

4. Itemsize --> returns the size (in bytes) of each element of a NumPy array.  If integers throws 4, if float throws 8

In [73]:
a.itemsize  #int

4

In [74]:
a1.itemsize   #float

8

In [75]:
a2.itemsize  #int

4

5. dtype --> gives datatype of the elements stored in a NumPy array

In [77]:
a.dtype

dtype('int32')

In [78]:
a1.dtype

dtype('float64')

In [79]:
a2.dtype

dtype('int32')

6. astype  --> Converting one datatype array to other

astype is used in machine learning where data needs to be cleaned lets take an example in some data there are age of a person in float so to reduce the size of data, astype is used.
 

In [83]:
a2.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [84]:
a2.dtype

dtype('int32')

In [85]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a2.astype('float')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [87]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])