In [23]:
import numpy as np

In [24]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
a=np.arange(24).reshape(12,2)  #shape the order of matrix in different styles, where 12 = rows and 2= columns
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [26]:
a=np.arange(24).reshape(6,4)  
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
a1=np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [28]:
a1[2]

3

In [29]:
a1[2:4]

array([3, 4])

In [30]:
a1[2:3]

array([3])

In [31]:
a1[-1]

5

In [32]:
a1[-5]

1

In [33]:
a1[-5:3]

array([1, 2, 3])

In [34]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
a[2]  #third row is returned

array([ 8,  9, 10, 11])

In [38]:
a[:,1]  #second column is returned

array([ 1,  5,  9, 13, 17, 21])

In [39]:
a[:,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [41]:
a[2:4,1:3]


array([[ 9, 10],
       [13, 14]])

In [45]:
a[4:,2:]

array([[18, 19],
       [22, 23]])

In [46]:
a[4:6,2:4]

array([[18, 19],
       [22, 23]])

Iterations

In [47]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [50]:
for i in np.nditer(a): #prints elements of each row*columns
    print(i) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
