In [1]:
import numpy as np

In [2]:
a1=np.arange(1,7)
a2=np.arange(4,10)

In [3]:
a1

array([1, 2, 3, 4, 5, 6])

In [4]:
a2

array([4, 5, 6, 7, 8, 9])

In [5]:
a1-a2

array([-3, -3, -3, -3, -3, -3])

In [6]:
a1*a2  #vector multiplications

array([ 4, 10, 18, 28, 40, 54])

In [8]:
a1*2  #scalar multiplications

array([ 2,  4,  6,  8, 10, 12])

In [9]:
a2>3

array([ True,  True,  True,  True,  True,  True])

In [10]:
a1<4

array([ True,  True,  True, False, False, False])

In [11]:
a3=np.arange(6).reshape(2,3)
a4=np.arange(6,12).reshape(3,2)

In [12]:
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
a4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
a3.dot(a4) #dot operation of 2*3 and 3*2 matrix checks if 3 and 3 are equal if yes then returns 2 and 2 matrix

array([[ 28,  31],
       [100, 112]])

In [15]:
a1.dot(a3) #throws error

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [16]:
a4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [17]:
a4.max()

11

In [18]:
a4.min()

6

In [20]:
a4.min(axis=0)  #gives column wise least value

array([6, 7])

In [22]:
a4.min(axis=1)  #gives min value from each of the rows

array([ 6,  8, 10])

In [23]:
a4.sum()

51

In [24]:
a4.sum(axis=0)  #column wise sum is returned

array([24, 27])

In [25]:
a4.mean()

8.5

In [27]:
np.mean(a4)

8.5

In [28]:
np.median(a4)

8.5

In [32]:
a4.std()

1.707825127659933

In [33]:
np.std(a4)

1.707825127659933

In [34]:
np.sin(a4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [35]:
np.exp(a4) #exponent

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])