In [1]:
import numpy as np


In [3]:
a4=np.arange(6,12).reshape(3,2)
a4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
a4.ndim

2

In [5]:
a4.ravel() #converts higher order arrays to 1 D

array([ 6,  7,  8,  9, 10, 11])

In [7]:
a4.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
a4.reshape(3,2)

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
a4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [12]:
a4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
a3=np.arange(1,7).reshape(3,2)
a3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.hstack((a3,a4))

array([[ 1,  2,  6,  7],
       [ 3,  4,  8,  9],
       [ 5,  6, 10, 11]])

In [16]:
np.vstack((a3,a4))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
np.hsplit(a4,2)

[array([[ 6],
        [ 8],
        [10]]),
 array([[ 7],
        [ 9],
        [11]])]

In [22]:
np.vsplit(a4,3)

[array([[6, 7]]), array([[8, 9]]), array([[10, 11]])]