In [1]:
import numpy as np

In [2]:
a=np.arange(24).reshape(6,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Take Random rows like 1st, 3rd and 4th row. We cannot do these operations from slicing and indexing so there is required Fancy Indexing.


In [6]:
a[[0,2,4]]


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [7]:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])