In [13]:
import numpy as np

In [14]:
a=np.random.randint(low=1,high=100,size=20).reshape(4,5)
a

array([[24, 38, 55,  4, 52],
       [66, 68, 55, 44,  4],
       [14, 49, 48,  9, 13],
       [ 3, 87, 51,  7, 23]])

get items that are greater than 50

In [15]:
a>50  #get an array of true or false

array([[False, False,  True, False,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False,  True,  True, False, False]])

In [16]:
#Indexing using Boolean Array/ Filtering  --> This method is very scalable
a[a>50]  #get an array of items that are True and returns the items that are greater than 50

array([55, 52, 66, 68, 55, 87, 51])

In [21]:
a[(a>50)&(a%2!=0)]  #items that are greater then 50 and odd

array([], dtype=int32)

In [18]:
a

array([[24, 38, 55,  4, 52],
       [66, 68, 55, 44,  4],
       [14, 49, 48,  9, 13],
       [ 3, 87, 51,  7, 23]])

In [19]:
a[(a>50)&(a%2!=0)] = 0 #putting value explicitly to 0 to those values in an arrray which is greater than 50 and odd
a

array([[24, 38,  0,  4, 52],
       [66, 68,  0, 44,  4],
       [14, 49, 48,  9, 13],
       [ 3,  0,  0,  7, 23]])