In [18]:
import numpy as np

Brodcasting:
Ability of NumPy to treat arrays of different shapes during Arithmetic Operations. Arithmetic Oprns on arrays are usually done on corresponding elements. Lets take an example of 3x3 mat multiplied by 1x3 then every row of 3*3 mat is multiplied by 1*3 which is broadcasting!!!!!


In [19]:
# Example
a1=np.arange(9).reshape(3,3)
a2=np.arange(3).reshape(1,3)
print(a1)
print()
print(a2)


c=a1+a2
print()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]]

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


Rules for Broadcasting

In [20]:
#1. If x=m and y=n, operation will take place regularly
a1=np.arange(8).reshape(2,4)  #reshape(x,y)
a2=np.arange(8,16).reshape(2,4)  #reshape(m,n)

a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [21]:
#2. If x=1 and y=n,then also operation will take place but with broadcast method (same dimension)
a1=np.arange(3).reshape(1,3)  #reshape(x,y)
a2=np.arange(12).reshape(4,3)  #reshape(m,n)
print(a1)
print()
print(a2)

print()
print(a2+a1)


[[0 1 2]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [22]:
#3. If y=1 and x=m,then also operation will take place but with broadcast method (same dimension)
a1=np.arange(4).reshape(4,1)
a2=np.arange(12).reshape(4,3)
print(a1)
print()
print(a2)

print()
print(a2+a1)

[[0]
 [1]
 [2]
 [3]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [23]:
#4. If x=1 and y!=n,then operation will not take place cause not of same dimension
a1=np.arange(3).reshape(1,3)  #reshape(x,y)
a2=np.arange(16).reshape(4,4) #reshape(m,n)
print(a1)
print()
print(a2)

print()
print(a2+a1)  #shows error

[[0 1 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



ValueError: operands could not be broadcast together with shapes (4,4) (1,3) 

In [ ]:
#5. If x=1 and n=1,then check if y==m to run the operation if yes then runs
a1=np.arange(3).reshape(1,3) #reshape(x,y)
a2=np.arange(4,7).reshape(3,1) #reshape(m,n)
print(a1)
print()
print(a2)

print()
print(a2+a1)  

[[0 1 2]]

[[4]
 [5]
 [6]]

[[4 5 6]
 [5 6 7]
 [6 7 8]]


In [27]:
#6. If x=1 and y=1,then operations runs
a1=np.arange(1).reshape(1,1) #reshape(x,y)
a2=np.arange(12).reshape(3,4) #reshape(m,n)
print(a1)
print()
print(a2)

print("\nThe output is:\n")
print(a2+a1)  

[[0]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

The output is:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
