In [37]:
import numpy as np


In [38]:
np.random.random()  #get random numbers between 0 and 1 everytime

0.1242709619721647

In [39]:
np.random.seed(1) #get same random numbers again and again every time I run the program using seed function
np.random.random()

0.417022004702574

In [40]:
np.random.uniform(3,10) #get random values in floating point between the starting point and ending point or within a given range

8.042271454095108

In [41]:
np.random.uniform(1,100,10)  #get an array of random values between 1 and 100 of size 10

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [42]:
np.random.uniform(1,100,10).reshape(5,2)

array([[21.24077272, 87.9336262 ],
       [ 3.71137173, 67.37628351],
       [42.31317543, 56.31029302],
       [14.89830692, 20.61204742],
       [80.2737123 , 96.857896  ]])

In [43]:
np.random.uniform(1,100,10).reshape(2,5)

array([[32.02899364, 69.53993895, 87.76252608, 89.56605969,  9.41937693],
       [ 4.86642354, 17.81321154, 87.93610784, 10.73633655, 42.68965488]])

In [44]:

np.random.uniform(1,100,10).reshape(10,1)

array([[95.83106348],
       [53.78336321],
       [69.49583428],
       [32.23604747],
       [68.96359184],
       [83.62794152],
       [ 2.81053946],
       [75.26428718],
       [98.8972478 ],
       [75.06839978]])

In [45]:
np.random.uniform(1,100,10).reshape(1,10)

array([[28.76395521, 79.13865352, 11.21937465, 45.34145909, 90.95095481,
        30.06780069, 29.48975852, 13.87282864,  2.91732883, 68.20471776]])

In [48]:
np.random.randint(1,10)  #generate a single random integer value between 1 and 10 everytime

1

In [52]:
np.random.randint(1,10,5) #generate an array of random integer value between 1 and 10 everytime of size 5

array([5, 6, 7, 3, 6])

In [53]:
np.random.randint(1,20,15).reshape(3,5)

array([[12,  8, 14,  9, 12],
       [13, 12,  5,  8,  8],
       [14,  5, 17, 19,  1]])

In [66]:
a=np.random.randint(1,10,6)
a

array([6, 2, 5, 7, 1, 7])

In [67]:
a.max()

7

In [68]:
np.max(a) #returns the maximum value

7

In [69]:
np.min(a)

1

In [70]:
np.argmax(a)  #returns the index of maximum value

3

In [71]:
np.argmin(a)

4

In [72]:
a[np.argmax(a)] #gives the maximum value

7

In [73]:
a[np.argmin(a)]

1

In [74]:
#replace all the odd digits by -1
a=np.random.randint(1,10,6)
a

array([6, 2, 3, 2, 6, 5])

In [97]:
a[a%2!=0]=-1
a

-1

In [76]:
# where(condition,True,False) #used to modify the array and store it to a new array--> the where function is like ternary condition

In [80]:
a=np.random.randint(1,200,6)
a

array([102,  22,  41,  78, 178, 114])

In [92]:
out=np.where(a%2!=0,-1,a)
out

array([ 46, 196,  -1,  -1,  -1,  -1])

In [93]:
out

array([ 46, 196,  -1,  -1,  -1,  -1])

In [94]:
a=np.random.randint(1,200,6)
a

array([158,  64,  76,  36, 182,  34])

In [95]:
out=np.where(a%2!=0,-1,2)
out

array([2, 2, 2, 2, 2, 2])

In [96]:
out

array([2, 2, 2, 2, 2, 2])

In [104]:
a=np.random.randint(1,200,10)
a

array([137, 110, 100,  33,   9,  85,  51,  80, 170,  65])

In [105]:
np.sort(a)

array([  9,  33,  51,  65,  80,  85, 100, 110, 137, 170])

In [106]:
np.percentile(a,100)

170.0

In [107]:
np.percentile(a,25)

54.5